let selectIcon = (code, pod = "d") => {
  if (pod === "d") {
    switch (code) {
      case "200":
          return "wi-day-storm-showers";
      case "201":
          return "wi-day-thunderstorm";
      case "202":
          return "wi-day-thunderstorm";
      case "230":
          return "wi-day-lightning";
      case "231":
          return "wi-day-lightning";
      case "232":
          return "wi-day-lightning";
      case "233":
          return "wi-day-sleet-storm";
      case "300":
          return "wi-day-sprinkle";
      case "301":
          return "wi-day-sprinkle";
      case "302":
          return "wi-day-sprinkle";
      case "500":
          return "wi-day-rain";
      case "501":
          return "wi-day-rain";
      case "502":
          return "wi-day-rain";
      case "511":
          return "wi-day-hail";
      case "520":
          return "wi-day-showers";
      case "521":
          return "wi-day-showers";
      case "522":
          return "wi-day-showers";
      case "600":
          return "wi-day-snow";
      case "601":
          return "wi-day-snow";
      case "602":
          return "wi-day-snow";
      case "610":
          return "wi-day-rain-mix";
      case "611":
          return "wi-day-sleet";
      case "612":
          return "wi-day-sleet";
      case "621":
          return "wi-day-snow";
      case "622":
          return "wi-day-snow";
      case "623":
          return "wi-day-snow";
      case "700":
          return "wi-day-haze";
      case "711":
          return "wi-day-haze";
      case "721":
          return "wi-day-haze";
      case "731":
          return "wi-day-fog";
      case "741":
          return "wi-day-fog";
      case "751":
          return "wi-day-fog";
      case "800":
          return "wi-day-sunny";
      case "801":
          return "wi-day-cloudy";
      case "802":
          return "wi-day-cloudy";
      case "803":
          return "wi-day-cloudy";
      case "804":
          return "wi-day-cloudy";
      case "900":
          return "wi-day-rain-mix";
    }
  }
  else if (pod === "n") {
    switch (code) {
      case "200":
          return "wi-night-alt-storm-showers";
      case "201":
          return "wi-night-alt-thunderstorm";
      case "202":
          return "wi-night-alt-thunderstorm";
      case "230":
          return "wi-night-alt-lightning";
      case "231":
          return "wi-night-alt-lightning";
      case "232":
          return "wi-night-alt-lightning";
      case "233":
          return "wi-night-alt-sleet-storm";
      case "300":
          return "wi-night-alt-sprinkle";
      case "301":
          return "wi-night-alt-sprinkle";
      case "302":
          return "wi-night-alt-sprinkle";
      case "500":
          return "wi-night-alt-rain";
      case "501":
          return "wi-night-alt-rain";
      case "502":
          return "wi-night-alt-rain";
      case "511":
          return "wi-night-alt-hail";
      case "520":
          return "wi-night-alt-showers";
      case "521":
          return "wi-night-alt-showers";
      case "522":
          return "wi-night-alt-showers";
      case "600":
          return "wi-night-alt-snow";
      case "601":
          return "wi-night-alt-snow";
      case "602":
          return "wi-night-alt-snow";
      case "610":
          return "wi-night-alt-rain-mix";
      case "611":
          return "wi-night-alt-sleet";
      case "612":
          return "wi-night-alt-sleet";
      case "621":
          return "wi-night-alt-snow";
      case "622":
          return "wi-night-alt-snow";
      case "623":
          return "wi-night-alt-snow";
      case "700":
          return "wi-night-fog";
      case "711":
          return "wi-night-fog";
      case "721":
          return "wi-night-fog";
      case "731":
          return "wi-night-fog";
      case "741":
          return "wi-night-fog";
      case "751":
          return "wi-night-fog";
      case "800":
          return "wi-night-clear";
      case "801":
          return "wi-night-alt-cloudy";
      case "802":
          return "wi-night-alt-cloudy";
      case "803":
          return "wi-night-alt-cloudy";
      case "804":
          return "wi-night-alt-cloudy";
      case "900":
          return "wi-night-alt-rain-mix";
    }
  }
};

module.exports = selectIcon;
